name: e_tantana
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  url_launcher: ^6.3.2
  cupertino_icons: ^1.0.8
  hugeicons: ^0.0.11
  flutter_staggered_grid_view: ^0.7.0
  carousel_slider: ^5.0.0
  smooth_page_indicator: ^1.2.0+3
  board_datetime_picker: ^2.8.3
  flutter_riverpod: ^2.0.0
  shared_preferences: ^2.2.3
  supabase_flutter: ^2.9.0
  path_provider: ^2.1.5
  path: ^1.9.1
  flutter_advanced_segment: ^3.1.0
  parallax_cards: ^1.0.2
  panorama_viewer: ^2.0.7
  internet_connection_checker_plus: ^2.8.0
  uuid: ^4.5.1
  riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  loading_animation_widget: ^1.3.0
  device_preview: ^1.2.0
  google_sign_in: ^6.3.0
  mime: ^2.0.0
  liquid_glass: ^0.0.2
  animated_bottom_navigation_bar: ^1.4.0
  sqflite: ^2.4.2
  table_calendar: ^3.1.3
  rename: ^3.1.0
  flutter_osm_plugin: ^1.4.2
  encrypt: ^5.0.3
  flutter_secure_storage: ^9.2.4
  crypto: ^3.0.6
  skeletonizer: ^1.4.3
  image_picker: ^1.1.2
  permission_handler: ^12.0.0+1
  video_thumbnail: ^0.5.6
  async: ^2.12.0
  video_player: ^2.10.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  cached_network_image: ^3.4.1
  flutter_cache_manager: ^3.4.1
  fl_chart: ^1.0.0
  flutter_screenutil: ^5.9.3
  restart_app: ^1.3.2
  equatable: ^2.0.7

  # for medias ---
  flutter_image_compress: ^2.4.0
  video_compress: ^3.1.4
  screenshot: ^3.0.0

  # pull refresh ----
  custom_refresh_indicator: ^4.0.1

  # for logique state ----
  get_it: ^9.2.0

  #for open street map -----
  geolocator: ^14.0.2
  geocoding: ^4.0.0
  http: ^1.5.0

  # UI kit ---------
  json_theme: ^8.0.0+3
  intl: ^0.19.0
  dartz: ^0.10.1
  share_plus: ^10.1.0
  interactive_viewer_2: ^0.1.0
  toastification: ^3.0.3
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true

  assets:
    - assets/medias/logos/
    - assets/medias/icons/
    - assets/theme/

  fonts:
    - family: Nonito
      fonts:
        - asset: assets/fonts/Nunito/Nunito-Regular.ttf
          weight: 600
    - family: BrunoAceSC
      fonts:
        - asset: assets/fonts/brunoAceSC/BrunoAceSC-Regular.ttf
    
flutter_launcher_icons:
  image_path: "assets/medias/icons/app_icon.png"
  android:
    notification_icon: "notification_icon"
    adaptive_icon_background: "#ffffff"
    adaptive_icon_foreground: "assets/medias/icons/app_icon.png"
  ios:
    image_path: "assets/medias/icons/app_icon.png"
  
  web:
    image_path: "assets/medias/icons/app_icon.png"
    background_color: "#ffffff"